export const STEP_REQUIRED_FIELDS: Record<string, string[]> = {
  "landing-zone": ["global.lzBmcIP"],
  storage: ["global.storage_plugin"],
  aap: ["global.aapDefaults.aapLicenseFile"],
  osac: ["global.osacAapLicenseFile"],
  caas: ["global.osacDnsClass", "global.osacDnsZone"],
  "hub-cluster": [
    "global.baseDomain",
    "global.clusterName",
    "global.machineNetwork",
    "global.apiVIP",
    "global.ingressVIP",
    "global.rendezvousIP",
    "global.defaultDNS",
    "global.defaultGateway",
    "global.defaultPrefix",
    "global.pullSecret",
    "global.sshPubKey",
    "global.agentHosts",
  ],
};
