/* tslint:disable */
/* eslint-disable */
/**
 * Enclave Configuration Wizard
 * API for managing Enclave deployment configuration files on the Landing Zone.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { LVMSStorageConfig } from './LVMSStorageConfig.js';
import {
    LVMSStorageConfigFromJSON,
    LVMSStorageConfigFromJSONTyped,
    LVMSStorageConfigToJSON,
    LVMSStorageConfigToJSONTyped,
} from './LVMSStorageConfig.js';
import type { VASTConfig } from './VASTConfig.js';
import {
    VASTConfigFromJSON,
    VASTConfigFromJSONTyped,
    VASTConfigToJSON,
    VASTConfigToJSONTyped,
} from './VASTConfig.js';
import type { ODFConfig } from './ODFConfig.js';
import {
    ODFConfigFromJSON,
    ODFConfigFromJSONTyped,
    ODFConfigToJSON,
    ODFConfigToJSONTyped,
} from './ODFConfig.js';
import type { QuayBackendRGWConfiguration } from './QuayBackendRGWConfiguration.js';
import {
    QuayBackendRGWConfigurationFromJSON,
    QuayBackendRGWConfigurationFromJSONTyped,
    QuayBackendRGWConfigurationToJSON,
    QuayBackendRGWConfigurationToJSONTyped,
} from './QuayBackendRGWConfiguration.js';
import type { HostEntry } from './HostEntry.js';
import {
    HostEntryFromJSON,
    HostEntryFromJSONTyped,
    HostEntryToJSON,
    HostEntryToJSONTyped,
} from './HostEntry.js';
import type { VASTVipPool } from './VASTVipPool.js';
import {
    VASTVipPoolFromJSON,
    VASTVipPoolFromJSONTyped,
    VASTVipPoolToJSON,
    VASTVipPoolToJSONTyped,
} from './VASTVipPool.js';

/**
 * 
 * @export
 * @interface GlobalConfig
 */
export interface GlobalConfig {
    /**
     * Control plane nodes (exactly 3)
     * @type {Array<HostEntry>}
     * @memberof GlobalConfig
     */
    agentHosts: Array<HostEntry> | null;
    /**
     * Virtual IP for Kubernetes API server
     * @type {string}
     * @memberof GlobalConfig
     */
    apiVIP: string;
    /**
     * Base DNS domain for the cluster
     * @type {string}
     * @memberof GlobalConfig
     */
    baseDomain: string;
    /**
     * OpenShift cluster name
     * @type {string}
     * @memberof GlobalConfig
     */
    clusterName: string;
    /**
     * DNS server IP for cluster nodes
     * @type {string}
     * @memberof GlobalConfig
     */
    defaultDNS: string;
    /**
     * Default gateway IP for cluster nodes
     * @type {string}
     * @memberof GlobalConfig
     */
    defaultGateway: string;
    /**
     * Additional NTP server addresses
     * @type {Array<string>}
     * @memberof GlobalConfig
     */
    defaultNtpServers?: Array<string> | null;
    /**
     * Subnet prefix length
     * @type {number}
     * @memberof GlobalConfig
     */
    defaultPrefix: number;
    /**
     * Air-gapped deployment mode (default: true)
     * @type {boolean}
     * @memberof GlobalConfig
     */
    disconnected?: boolean;
    /**
     * Enable TPM v2 disk encryption
     * @type {boolean}
     * @memberof GlobalConfig
     */
    diskEncryption?: boolean;
    /**
     * Plugins to deploy
     * @type {Array<string>}
     * @memberof GlobalConfig
     */
    enabledPlugins?: Array<string> | null;
    /**
     * OSAC deployment profile
     * @type {string}
     * @memberof GlobalConfig
     */
    osacProfile?: string;
    /**
     * Path to AAP license manifest.zip on the landing zone
     * @type {string}
     * @memberof GlobalConfig
     */
    osacAapLicenseFile?: string;
    /**
     * Use external PostgreSQL instead of built-in
     * @type {boolean}
     * @memberof GlobalConfig
     */
    osacBYODatabase?: boolean;
    /**
     * PostgreSQL connection URL when using BYO database
     * @type {string}
     * @memberof GlobalConfig
     */
    osacDatabaseUrl?: string;
    /**
     * Fully-qualified Ansible role name of the DNS driver
     * @type {string}
     * @memberof GlobalConfig
     */
    osacDnsClass?: string;
    /**
     * DNS zone to operate in (defaults to EXTERNAL_ACCESS_BASE_DOMAIN)
     * @type {string}
     * @memberof GlobalConfig
     */
    osacDnsZone?: string;
    /**
     * Number of Keycloak replicas
     * @type {number}
     * @memberof GlobalConfig
     */
    rhbkInstances?: number;
    /**
     * Deploy PostgreSQL alongside Keycloak
     * @type {boolean}
     * @memberof GlobalConfig
     */
    rhbkDeployDatabase?: boolean;
    /**
     * PVC size for Keycloak PostgreSQL
     * @type {string}
     * @memberof GlobalConfig
     */
    rhbkDbSize?: string;
    /**
     * Virtual IP for ingress wildcard
     * @type {string}
     * @memberof GlobalConfig
     */
    ingressVIP: string;
    /**
     * LVMS device selector configuration
     * @type {LVMSStorageConfig}
     * @memberof GlobalConfig
     */
    lvmsConfig?: LVMSStorageConfig;
    /**
     * DNS hostname for landing zone BMC interface
     * @type {string}
     * @memberof GlobalConfig
     */
    lzBmcHostname?: string;
    /**
     * Landing zone BMC IP for boot ISO serving
     * @type {string}
     * @memberof GlobalConfig
     */
    lzBmcIP: string;
    /**
     * Network CIDR for cluster nodes
     * @type {string}
     * @memberof GlobalConfig
     */
    machineNetwork: string;
    /**
     * Maximum pods per node (default: 500)
     * @type {number}
     * @memberof GlobalConfig
     */
    masterMaxPods?: number;
    /**
     * oc-mirror log level
     * @type {string}
     * @memberof GlobalConfig
     */
    ocMirrorLogLevel?: GlobalConfigOcMirrorLogLevelEnum;
    /**
     * ODF deployment configuration
     * @type {ODFConfig}
     * @memberof GlobalConfig
     */
    odfDefaults?: ODFConfig;
    /**
     * ODF external Ceph cluster config JSON (required when storage_plugin is odf)
     * @type {string}
     * @memberof GlobalConfig
     */
    odfExternalConfig?: string;
    /**
     * 
     * @type {any}
     * @memberof GlobalConfig
     */
    pullSecret: any | null;
    /**
     * Quay image storage backend
     * @type {string}
     * @memberof GlobalConfig
     */
    quayBackend: GlobalConfigQuayBackendEnum;
    /**
     * RadosGW/S3 backend config (required when quayBackend is RadosGWStorage)
     * @type {QuayBackendRGWConfiguration}
     * @memberof GlobalConfig
     */
    quayBackendRGWConfiguration?: QuayBackendRGWConfiguration;
    /**
     * Admin password for Quay registry
     * @type {string}
     * @memberof GlobalConfig
     */
    quayPassword: string;
    /**
     * Admin username for Quay registry
     * @type {string}
     * @memberof GlobalConfig
     */
    quayUser: string;
    /**
     * IP of first control-plane node
     * @type {string}
     * @memberof GlobalConfig
     */
    rendezvousIP: string;
    /**
     * Path to SSH public key file
     * @type {string}
     * @memberof GlobalConfig
     */
    sshPubKey: string;
    /**
     * Storage plugin
     * @type {string}
     * @memberof GlobalConfig
     */
    storagePlugin: GlobalConfigStoragePluginEnum;
    /**
     * VAST management API password
     * @type {string}
     * @memberof GlobalConfig
     */
    vastAdminPassword?: string;
    /**
     * VAST management API username
     * @type {string}
     * @memberof GlobalConfig
     */
    vastAdminUsername?: string;
    /**
     * VAST CSI deployment defaults
     * @type {VASTConfig}
     * @memberof GlobalConfig
     */
    vastDefaults?: VASTConfig;
    /**
     * VAST management endpoint URL (required when storage_plugin is vast-csi)
     * @type {string}
     * @memberof GlobalConfig
     */
    vastEndpoint?: string;
    /**
     * VIP pool configuration for CSI traffic (required when storage_plugin is vast-csi)
     * @type {VASTVipPool}
     * @memberof GlobalConfig
     */
    vastVipPool?: VASTVipPool;
    /**
     * Absolute path to root working directory
     * @type {string}
     * @memberof GlobalConfig
     */
    workingDir: string;
}


/**
 * @export
 */
export const GlobalConfigOcMirrorLogLevelEnum = {
    Trace: 'trace',
    Debug: 'debug',
    Info: 'info',
    Error: 'error'
} as const;
export type GlobalConfigOcMirrorLogLevelEnum = typeof GlobalConfigOcMirrorLogLevelEnum[keyof typeof GlobalConfigOcMirrorLogLevelEnum];

/**
 * @export
 */
export const GlobalConfigQuayBackendEnum = {
    RadosGwStorage: 'RadosGWStorage',
    LocalStorage: 'LocalStorage'
} as const;
export type GlobalConfigQuayBackendEnum = typeof GlobalConfigQuayBackendEnum[keyof typeof GlobalConfigQuayBackendEnum];

/**
 * @export
 */
export const GlobalConfigStoragePluginEnum = {
    Lvms: 'lvms',
    Odf: 'odf',
    VastCsi: 'vast-csi'
} as const;
export type GlobalConfigStoragePluginEnum = typeof GlobalConfigStoragePluginEnum[keyof typeof GlobalConfigStoragePluginEnum];


/**
 * Check if a given object implements the GlobalConfig interface.
 */
export function instanceOfGlobalConfig(value: object): value is GlobalConfig {
    if (!('agentHosts' in value) || value['agentHosts'] === undefined) return false;
    if (!('apiVIP' in value) || value['apiVIP'] === undefined) return false;
    if (!('baseDomain' in value) || value['baseDomain'] === undefined) return false;
    if (!('clusterName' in value) || value['clusterName'] === undefined) return false;
    if (!('defaultDNS' in value) || value['defaultDNS'] === undefined) return false;
    if (!('defaultGateway' in value) || value['defaultGateway'] === undefined) return false;
    if (!('defaultPrefix' in value) || value['defaultPrefix'] === undefined) return false;
    if (!('ingressVIP' in value) || value['ingressVIP'] === undefined) return false;
    if (!('lzBmcIP' in value) || value['lzBmcIP'] === undefined) return false;
    if (!('machineNetwork' in value) || value['machineNetwork'] === undefined) return false;
    if (!('pullSecret' in value) || value['pullSecret'] === undefined) return false;
    if (!('quayBackend' in value) || value['quayBackend'] === undefined) return false;
    if (!('quayPassword' in value) || value['quayPassword'] === undefined) return false;
    if (!('quayUser' in value) || value['quayUser'] === undefined) return false;
    if (!('rendezvousIP' in value) || value['rendezvousIP'] === undefined) return false;
    if (!('sshPubKey' in value) || value['sshPubKey'] === undefined) return false;
    if (!('workingDir' in value) || value['workingDir'] === undefined) return false;
    return true;
}

export function GlobalConfigFromJSON(json: any): GlobalConfig {
    return GlobalConfigFromJSONTyped(json, false);
}

export function GlobalConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'agentHosts': (json['agent_hosts'] == null ? null : (json['agent_hosts'] as Array<any>).map(HostEntryFromJSON)),
        'apiVIP': json['apiVIP'],
        'baseDomain': json['baseDomain'],
        'clusterName': json['clusterName'],
        'defaultDNS': json['defaultDNS'],
        'defaultGateway': json['defaultGateway'],
        'defaultNtpServers': json['defaultNtpServers'] == null ? undefined : json['defaultNtpServers'],
        'defaultPrefix': json['defaultPrefix'],
        'disconnected': json['disconnected'] == null ? undefined : json['disconnected'],
        'diskEncryption': json['diskEncryption'] == null ? undefined : json['diskEncryption'],
        'enabledPlugins': json['enabled_plugins'] == null ? undefined : json['enabled_plugins'],
        'osacProfile': json['osacProfile'] == null ? undefined : json['osacProfile'],
        'osacAapLicenseFile': json['osacAapLicenseFile'] == null ? undefined : json['osacAapLicenseFile'],
        'osacBYODatabase': json['osacBYODatabase'] == null ? undefined : json['osacBYODatabase'],
        'osacDatabaseUrl': json['osacDatabaseUrl'] == null ? undefined : json['osacDatabaseUrl'],
        'osacDnsClass': json['osacDnsClass'] == null ? undefined : json['osacDnsClass'],
        'osacDnsZone': json['osacDnsZone'] == null ? undefined : json['osacDnsZone'],
        'rhbkInstances': json['rhbk_instances'] == null ? undefined : json['rhbk_instances'],
        'rhbkDeployDatabase': json['rhbk_deploy_database'] == null ? undefined : json['rhbk_deploy_database'],
        'rhbkDbSize': json['rhbk_db_size'] == null ? undefined : json['rhbk_db_size'],
        'ingressVIP': json['ingressVIP'],
        'lvmsConfig': json['lvmsConfig'] == null ? undefined : LVMSStorageConfigFromJSON(json['lvmsConfig']),
        'lzBmcHostname': json['lzBmcHostname'] == null ? undefined : json['lzBmcHostname'],
        'lzBmcIP': json['lzBmcIP'],
        'machineNetwork': json['machineNetwork'],
        'masterMaxPods': json['masterMaxPods'] == null ? undefined : json['masterMaxPods'],
        'ocMirrorLogLevel': json['ocMirrorLogLevel'] == null ? undefined : json['ocMirrorLogLevel'],
        'odfDefaults': json['odfDefaults'] == null ? undefined : ODFConfigFromJSON(json['odfDefaults']),
        'odfExternalConfig': json['odfExternalConfig'] == null ? undefined : json['odfExternalConfig'],
        'pullSecret': json['pullSecret'],
        'quayBackend': json['quayBackend'],
        'quayBackendRGWConfiguration': json['quayBackendRGWConfiguration'] == null ? undefined : QuayBackendRGWConfigurationFromJSON(json['quayBackendRGWConfiguration']),
        'quayPassword': json['quayPassword'],
        'quayUser': json['quayUser'],
        'rendezvousIP': json['rendezvousIP'],
        'sshPubKey': json['sshPubKey'],
        'storagePlugin': json['storage_plugin'],
        'vastAdminPassword': json['vastAdminPassword'] == null ? undefined : json['vastAdminPassword'],
        'vastAdminUsername': json['vastAdminUsername'] == null ? undefined : json['vastAdminUsername'],
        'vastDefaults': json['vastDefaults'] == null ? undefined : VASTConfigFromJSON(json['vastDefaults']),
        'vastEndpoint': json['vastEndpoint'] == null ? undefined : json['vastEndpoint'],
        'vastVipPool': json['vastVipPool'] == null ? undefined : VASTVipPoolFromJSON(json['vastVipPool']),
        'workingDir': json['workingDir'],
    };
}

export function GlobalConfigToJSON(json: any): GlobalConfig {
    return GlobalConfigToJSONTyped(json, false);
}

export function GlobalConfigToJSONTyped(value?: GlobalConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'agent_hosts': (value['agentHosts'] == null ? null : (value['agentHosts'] as Array<any>).map(HostEntryToJSON)),
        'apiVIP': value['apiVIP'],
        'baseDomain': value['baseDomain'],
        'clusterName': value['clusterName'],
        'defaultDNS': value['defaultDNS'],
        'defaultGateway': value['defaultGateway'],
        'defaultNtpServers': value['defaultNtpServers'],
        'defaultPrefix': value['defaultPrefix'],
        'disconnected': value['disconnected'],
        'diskEncryption': value['diskEncryption'],
        'enabled_plugins': value['enabledPlugins'] ?? [],
        'osacProfile': value['osacProfile'],
        'osacAapLicenseFile': value['osacAapLicenseFile'],
        'osacBYODatabase': value['osacBYODatabase'],
        'osacDatabaseUrl': value['osacDatabaseUrl'],
        'osacDnsClass': value['osacDnsClass'],
        'osacDnsZone': value['osacDnsZone'],
        'rhbk_instances': value['rhbkInstances'],
        'rhbk_deploy_database': value['rhbkDeployDatabase'],
        'rhbk_db_size': value['rhbkDbSize'],
        'ingressVIP': value['ingressVIP'],
        'lvmsConfig': LVMSStorageConfigToJSON(value['lvmsConfig']),
        'lzBmcHostname': value['lzBmcHostname'],
        'lzBmcIP': value['lzBmcIP'],
        'machineNetwork': value['machineNetwork'],
        'masterMaxPods': value['masterMaxPods'],
        'ocMirrorLogLevel': value['ocMirrorLogLevel'],
        'odfDefaults': ODFConfigToJSON(value['odfDefaults']),
        'odfExternalConfig': value['odfExternalConfig'],
        'pullSecret': value['pullSecret'],
        'quayBackend': value['quayBackend'],
        'quayBackendRGWConfiguration': QuayBackendRGWConfigurationToJSON(value['quayBackendRGWConfiguration']),
        'quayPassword': value['quayPassword'],
        'quayUser': value['quayUser'],
        'rendezvousIP': value['rendezvousIP'],
        'sshPubKey': value['sshPubKey'],
        'storage_plugin': value['storagePlugin'],
        'vastAdminPassword': value['vastAdminPassword'],
        'vastAdminUsername': value['vastAdminUsername'],
        'vastDefaults': VASTConfigToJSON(value['vastDefaults']),
        'vastEndpoint': value['vastEndpoint'],
        'vastVipPool': VASTVipPoolToJSON(value['vastVipPool']),
        'workingDir': value['workingDir'],
    };
}

