// Code generated by schemagen. DO NOT EDIT.
package schema

type OsacConfig struct {
	OsacAapLicenseFile                                      string          `yaml:"osacAapLicenseFile" json:"osacAapLicenseFile" doc:"Path to AAP license manifest.zip file on the Landing Zone"`
	OsacBYODatabase                                         *bool           `yaml:"osacBYODatabase,omitempty" json:"osacBYODatabase,omitempty" doc:"Set to true to use an external database instead of the built-in dev postgres"`
	OsacChartVersion                                        *string         `yaml:"osacChartVersion,omitempty" json:"osacChartVersion,omitempty" doc:"OSAC Helm chart version to deploy (overrides default from defaults.yaml)" minLength:"1"`
	OsacDatabaseUrl                                         *string         `yaml:"osacDatabaseUrl,omitempty" json:"osacDatabaseUrl,omitempty" doc:"Connection URL for external database. When provided with osacBYODatabase=true, post-operators.yaml creates the fulfillment-db secret from this value. If omitted, the user must pre-create the fulfillment-db secret manually."`
	OsacDnsClass                                            *string         `yaml:"osacDnsClass,omitempty" json:"osacDnsClass,omitempty" doc:"Fully-qualified Ansible role name of the DNS driver" enum:"dns.route53.dns"`
	OsacDnsZone                                             *string         `yaml:"osacDnsZone,omitempty" json:"osacDnsZone,omitempty" doc:"DNS zone to operate in (defaults to EXTERNAL_ACCESS_BASE_DOMAIN)"`
	OsacNetrisAwsAccessKeyId                                *string         `yaml:"osacNetrisAwsAccessKeyId,omitempty" json:"osacNetrisAwsAccessKeyId,omitempty" doc:"AWS access key for Route53 DNS management"`
	OsacNetrisAwsSecretAccessKey                            *string         `yaml:"osacNetrisAwsSecretAccessKey,omitempty" json:"osacNetrisAwsSecretAccessKey,omitempty" doc:"AWS secret key for Route53 DNS management"`
	OsacNetrisControllerUrl                                 *string         `yaml:"osacNetrisControllerUrl,omitempty" json:"osacNetrisControllerUrl,omitempty" doc:"Netris controller API URL (e.g. https://ctl.netris.io)"`
	OsacNetrisEnabled                                       *bool           `yaml:"osacNetrisEnabled,omitempty" json:"osacNetrisEnabled,omitempty" doc:"Enable Netris network backend for cluster/network fulfillment"`
	OsacNetrisExternalAccessApiInternalNetwork              *string         `yaml:"osacNetrisExternalAccessApiInternalNetwork,omitempty" json:"osacNetrisExternalAccessApiInternalNetwork,omitempty" doc:"Internal network type for API access (e.g. 'hypershift')"`
	OsacNetrisExternalAccessBaseDomain                      *string         `yaml:"osacNetrisExternalAccessBaseDomain,omitempty" json:"osacNetrisExternalAccessBaseDomain,omitempty" doc:"DNS domain for cluster endpoints"`
	OsacNetrisExternalAccessSupportedBaseDomains            *string         `yaml:"osacNetrisExternalAccessSupportedBaseDomains,omitempty" json:"osacNetrisExternalAccessSupportedBaseDomains,omitempty" doc:"Comma-separated list of allowed base domains"`
	OsacNetrisHostedClusterBaseDomain                       *string         `yaml:"osacNetrisHostedClusterBaseDomain,omitempty" json:"osacNetrisHostedClusterBaseDomain,omitempty" doc:"Base domain for hosted clusters"`
	OsacNetrisHostedClusterControllerAvailabilityPolicy     *string         `yaml:"osacNetrisHostedClusterControllerAvailabilityPolicy,omitempty" json:"osacNetrisHostedClusterControllerAvailabilityPolicy,omitempty" doc:"Controller availability policy for hosted clusters" enum:"SingleReplica,HighlyAvailable"`
	OsacNetrisHostedClusterInfrastructureAvailabilityPolicy *string         `yaml:"osacNetrisHostedClusterInfrastructureAvailabilityPolicy,omitempty" json:"osacNetrisHostedClusterInfrastructureAvailabilityPolicy,omitempty" doc:"Infrastructure availability policy for hosted clusters" enum:"SingleReplica,HighlyAvailable"`
	OsacNetrisMgmtRouteDestination                          *string         `yaml:"osacNetrisMgmtRouteDestination,omitempty" json:"osacNetrisMgmtRouteDestination,omitempty" doc:"Management route CIDR (e.g. 10.8.0.0/30)"`
	OsacNetrisMgmtRouteGateway                              *string         `yaml:"osacNetrisMgmtRouteGateway,omitempty" json:"osacNetrisMgmtRouteGateway,omitempty" doc:"Management route gateway IP"`
	OsacNetrisMgmtVpcId                                     *string         `yaml:"osacNetrisMgmtVpcId,omitempty" json:"osacNetrisMgmtVpcId,omitempty" doc:"Management VPC ID in Netris"`
	OsacNetrisMgmtVpcName                                   *string         `yaml:"osacNetrisMgmtVpcName,omitempty" json:"osacNetrisMgmtVpcName,omitempty" doc:"Management VPC name in Netris"`
	OsacNetrisPassword                                      *string         `yaml:"osacNetrisPassword,omitempty" json:"osacNetrisPassword,omitempty" doc:"Netris API password"`
	OsacNetrisResourceClassMap                              *string         `yaml:"osacNetrisResourceClassMap,omitempty" json:"osacNetrisResourceClassMap,omitempty" doc:"JSON dict mapping resource classes to Netris server cluster templates"`
	OsacNetrisSiteId                                        *string         `yaml:"osacNetrisSiteId,omitempty" json:"osacNetrisSiteId,omitempty" doc:"Netris site ID (integer as string)"`
	OsacNetrisSshBastionHost                                *string         `yaml:"osacNetrisSshBastionHost,omitempty" json:"osacNetrisSshBastionHost,omitempty" doc:"SSH bastion hostname/IP for server management access"`
	OsacNetrisSshBastionKey                                 *string         `yaml:"osacNetrisSshBastionKey,omitempty" json:"osacNetrisSshBastionKey,omitempty" doc:"SSH private key for bastion host access"`
	OsacNetrisSshBastionUser                                *string         `yaml:"osacNetrisSshBastionUser,omitempty" json:"osacNetrisSshBastionUser,omitempty" doc:"SSH bastion username"`
	OsacNetrisSshKey                                        *string         `yaml:"osacNetrisSshKey,omitempty" json:"osacNetrisSshKey,omitempty" doc:"SSH private key for bare-metal server access"`
	OsacNetrisSshUser                                       *string         `yaml:"osacNetrisSshUser,omitempty" json:"osacNetrisSshUser,omitempty" doc:"SSH username for bare-metal servers (typically 'core')"`
	OsacNetrisStepsCollection                               *string         `yaml:"osacNetrisStepsCollection,omitempty" json:"osacNetrisStepsCollection,omitempty" doc:"Ansible steps collection for Netris (default: netris.steps)"`
	OsacNetrisTenantId                                      *string         `yaml:"osacNetrisTenantId,omitempty" json:"osacNetrisTenantId,omitempty" doc:"Netris tenant ID (integer as string)"`
	OsacNetrisTenantName                                    *string         `yaml:"osacNetrisTenantName,omitempty" json:"osacNetrisTenantName,omitempty" doc:"Netris tenant name"`
	OsacNetrisUsername                                      *string         `yaml:"osacNetrisUsername,omitempty" json:"osacNetrisUsername,omitempty" doc:"Netris API username"`
	OsacProfilesList                                        *[]string       `yaml:"osacProfilesList,omitempty" json:"osacProfilesList,omitempty" doc:"List of enabled service profiles: vmaas, caas, bmaas" minItems:"1"`
	OsacTestUsers                                           *bool           `yaml:"osacTestUsers,omitempty" json:"osacTestUsers,omitempty" doc:"Create test users in the Keycloak osac realm for initial UI/CLI access"`
	Images                                                  *map[string]any `yaml:"osac_images,omitempty" json:"osacImages,omitempty" doc:"Optional container image overrides. When unset, the Helm chart's built-in image references are used."`
}
